name: Scrape klook data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -sSLG "https://www.klook.com/v3/usrcsrv/search/city/activities?city_id=6&frontend_id_list=2,116,3,4,6,117,8,55&limit=29" -H "User-Agent: Mozilla/5.0" -H "accept-language: en_US" -H "x-klook-lang: en_US" -H "currency: SGD"| jq .result.items[].data > klook.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest klook activities: ${timestamp}" || exit 0
        git push
