name: Scrape klook data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -sSLG "https://www.klook.com/xos_api/v2/usrcsrv/search/city/6/activities?sort=publish_time&page=1&limit=50" -H "User-Agent: Mozilla/5.0" | jq . > klook.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest klook activities: ${timestamp}" || exit 0
        git push
