name: Scrape shopee data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl -sSLG "https://shopee.sg/api/v4/recommend/recommend?bundle=daily_discover_main&limit=500&offset=0" -H "User-Agent: Mozilla/5.0" -H "accept-language: en_US" | jq .data.sections[].data.item[] > shopee.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest sales: ${timestamp}" || exit 0
        git push
